apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discord-clone
  template:
    metadata:
      labels:
        app: discord-clone
    spec:
      containers:
      - name: discord-clone
        image: gcr.io/discord-clone-2023/discord-clone:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: discord-clone-secret
